version: '3.3'
services:
  frontend:
    image: xjt85/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env

  backend:
    image: xjt85/foodgram-backend:latest
    restart: always
    # command: bash -c ""
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    restart: always
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  postgres_data: